config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :registers
  resources :tournaments, only: [:index, :show]
  root 'static#home'

  get "/signup", to: "users#new" 
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new" 
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"
  
  get "/auth/github/callback", to: "sessions#github"

  get '/search', to: 'registers#search'

  resources :users do
    resources :registers, only: [:index, :show, :edit, :new]
  end

  get '*path' => redirect('/')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
  belongs_to :user
  belongs_to :tournament, optional: true
  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :handicap_category, presence: true

  scope :search_by_age, -> (age){where("age = ?", age)}
  scope :order_by_age, -> {order(:age)}
  scope :female, -> {where(gender: "female")}
  scope :order_by_name, -> {order(:name)}
  
  
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :registers
  has_many :users, through: :registers

  scope :order_by_tournament_name, -> {order(:name)}

  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :registers
  has_many :tournaments, through: :registers
  validates :email, presence: true
  validates :email, uniqueness: true

  # scope :order_by_email, -> {order(:email)}


  def self.find_or_create_from_omniauth(user_info)
    User.first_or_create(uid: user_info["uid"]) do |user|
      user.email = user_info["info"]["nickname"] + "@something.com"
      user.password = SecureRandom.hex
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  private
    def current_user
      User.find_by_id(session[:user_id]) if logged_in?
    end

    def logged_in?
      !!session[:user_id]
    end

    def require_login
      return head(:forbidden) unless session.include? :user_id
    end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :require_login

  def index
    if !params[:user].blank?
      @registers = Register.by_user(params[:user])
    elsif params[:user_id]
      @registers = User.find(params[:user_id]).registers
    else
      @registers = Register.all
    end
  end

  def search
    @registers = Register.search_by_age(params[:age])
    @registers = Register.order_by_age if @registers == []

    render :index
  end
  
  def show
    set_register
  end

  def new
    @register = Register.new
  end

  def create
    # @register = Register.new(register_params)
    #   if @register.save
    #   redirect_to register_path(@register)
    # else
    #   render :new
    # end
    @register = current_user.registers.build(register_params)
    
    if @register.save
      redirect_to register_path(@register)
    else
      @register.build_tournament unless @register.tournament
      render :new
    end
  end


  def edit
    set_register
    if @register.user != current_user
      redirect_to registers_path
    end
  end

  def update
    set_register
    if @register.user == current_user
      if @register.update(register_params) 
        redirect_to register_path(@register)
      else
        render :edit
      end
    else
      redirect_to registers_path
    end
    
  end

  def destroy
    set_register
    if @register.user == current_user
       @register.destroy
    end
       redirect_to registers_path
  end

  private
    def set_register
      @register = Register.find_by(id: params[:id])
      if !@register
        redirect_to registers_path
      end
    end

    def register_params
      params.require(:register).permit(:name, :age, :gender, :email, :phone, :handicap_category, :tournament_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  #login
  def create
    @user = User.find_by_email(user_params[:email])
  
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Username or Password was incorrect"
      redirect_to '/login'
    end
  end

  def github
    user = User.find_or_create_from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to user_path(user)
  end

  #logout
  def destroy
    session.clear
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

    def auth
      request.env["omniauth.auth"]
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home
    
  end

  

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def index
    @tournaments = Tournament.order_by_tournament_name
  end

  def show
    @tournament = Tournament.find(params[:id])
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     session[:user_id] = @user.user_id
  #     redirect_to tournaments_path
  #   else
  #     render :new
  #   end
  # end

  # i don't need this because using devise 
  # but then where do i need put redirect_to tournaments_path
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:index, :new, :create]

  def new
    @user = User.new
  end

  #signup
  def create
    @user = User.new(user_params)

    if @user.save 
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else

      render :new
    end
  end

  def index
    @users = User.all
    
  end

  def show
    @user = User.find(params[:id])
  end


  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<ul>
    <% object.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>

    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <style>
body {
  background-image: url("");
}
  </style>
    <title>RailsGolfTournamentRegistration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">-->

  </head>

  <body>
  <nav>
     <div class = "light-green lighten-2">
          <%= link_to "Home", root_path %>
          <%= link_to "Tournament", tournaments_path %>
          <% unless logged_in? %>
              <%= link_to "Signup", signup_path %>
              <%= link_to "Login", login_path %>

          <% else %>
              <%= link_to "My Pofile", user_path(current_user) %>
              <%= link_to "My Registration", user_registers_path(current_user) %>
              <%= link_to "All Registration", registers_path %>
              <%= link_to "Register Tournament", new_user_register_path(current_user) %>
              <%= link_to "Logout", logout_path, method: :delete %>

        
          <% end %>
      </div>
  </nav>
      <img src="https://previews.123rf.com/images/bsd555/bsd5551703/bsd555170300092/74630878-golf-ball-and-clubs-linear-icon-thin-line-illustration-golf-equipment-contour-symbol-vector-isolated.jpg" alt="no image" width="200px" height="150px" >
    <%= yield %>
    <!-- Compiled and minified JavaScript -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>-->
       
  </body>
</html>

app/views/registers/_form.html.erb
<style>
    .form{
         width: 500px;
        border: 2px solid green;
    }
</style>
<div class="form">
<p><strong><u>Registration Form</u></strong></p>
<%= form_for(@register) do |f| %>

<%= render partial: "layouts/errors", locals: {object: @register} %> 
<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :email %>
<%= f.text_field :email, placeholder: "email@something.com" %><br>

<%= f.label :phone %>
<%= f.text_field :phone, placeholder: "222-222-2222"%><br>

<%= f.label :age %>
<%= f.text_field :age %><br>

<%= f.label :gender %>
<%= f.text_field :gender, placeholder: "male or female" %><br>

<br>

<%= f.label :handicap_category %><br>
0 to 5<%= f.radio_button :handicap_category, '0 to 5'%><br>
6 to 12<%= f.radio_button :handicap_category, '6 to 12' %><br>
13 to 20<%= f.radio_button :handicap_category, '13 to 20' %><br>
21 to 28<%= f.radio_button :handicap_category, '21 to 28' %><br>
29 to 36<%= f.radio_button :handicap_category, '29 to 36' %><br>
above 36<%= f.radio_button :handicap_category, 'above 36' %><br>

Select Tournament: <%= f.collection_select :tournament_id, Tournament.all, :id, :name %>
<br>

<%= f.submit %>
<% end %>
<br>
</div>

app/views/registers/edit.html.erb
<h2>Edit Registration for User: <%= @register.user.email %></h2>
<br>
<%= render partial: "registers/form" %>

<br>
<%= button_to "Delete Registration", register_path(@register), method: :delete, data: { confirm: "Are you sure you want to delete this registration?"} %>

app/views/registers/index.html.erb
<h1>All Registrations</h1>

<% @registers.each do |r| %>
<h3><%= link_to r.tournament.name, register_path(r) %></h3>
<h3>Name: <%= r.name %></h3>
<h3>Age: <%= r.age %></h3>
<h3>Gender: <%= r.gender %></h3>


<h4>Registered User: <%= r.user.email %></h4>

<% end %>

<%= form_tag('/search', method: 'get') do %>
<%= label_tag(:age, "Search by age:") %>
 <%= text_field_tag(:age) %>
<%= submit_tag("SEARCH") %>
<% end %>

app/views/registers/new.html.erb
<%= render partial: "registers/form" %>

app/views/registers/show.html.erb
<h2>Registration Details</h2>

<p><%= @register.user.email %> 
<br>
<br>
Tournament Name: <%= link_to @register.tournament.name, tournament_path(@register.tournament) %> <br>
Name: <%= @register.name %><br>
Email: <%= @register.email %><br>
Phone: <%= @register.phone %><br>
Age: <%= @register.age %><br>
Gender: <%= @register.gender %><br>
Handicap Category: <%= @register.handicap_category %><br>
<br>
<%= link_to "EDIT", edit_user_register_path(@register.user, @register) if @register.user %></p>

app/views/tournaments/index.html.erb
<h1>Tournament List</h1>

<br>
<table border='1'>
  <tr>
    <th>Tournament Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Check in</th>
    <th>Shotgun Start</th>
    <th>Location</th>
    <th>Description</th>
  </tr>

  <tr>
    <td>
      <% @tournaments.each do |t| %>
      <%= link_to t.name, tournament_path(t) %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.start_date %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.end_date %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.check_in %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.shotgun_start %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.location %>
      <br>
      <% end %>
    </td>

    <td>
      <% @tournaments.each do |t| %>
      <%= t.description %>
      <br>
      <% end %>
    </td>
  </tr>
</table>
<br>

app/views/tournaments/show.html.erb
<br>
<br>
<%= link_to "Back to Tournament List", :tournaments%> <br><br>

<h2><%= @tournament.name %> Details</h2>

<b>Tournament Name:</b> <%= @tournament.name %><br><br>
<b>Start Date:</b> <%= @tournament.start_date %><br><br>
<b>End Date:</b> <%= @tournament.end_date %><br><br>
<b>Check-in:</b> <%= @tournament.check_in %><br><br>
<b>Shotgun start:</b> <%= @tournament.shotgun_start %><br><br>
<b>Location:</b> <%= @tournament.location %><br><br>
<b>Description:</b> <%= @tournament.description %><br><br>

app/views/users/index.html.erb
<style>
    .number, .login{
      width: 600px;
      border: 2px solid green;
    }
</style>

<div class=number>
    <h3><ul> There are <u><%= @users.count %></u> players are registered until today. </ul><h3>

</div>

<div>
    
</div>





<p>create account or login to register tournament</p>

<div class="login">
  <ul>
    <li><%= link_to "Signup as a new user", signup_path %></li>
    <li><%= link_to "Login as an existing user", login_path %></li>
  </ul>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user, url: signup_path do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>

    <% end %>
</ul>
<div>
    <%= f.label :email %>
    <%= f.text_field :email %>
</div>
<div>
    <%= f.label :password %>
    <%= f.password_field :password %>
</div>


<%= f.submit "Signup" %>
<% end %>

<%= link_to "Signup with Github", "/auth/github" %>

app/views/users/show.html.erb
<style>
  .click, .show{
     width: 500px;
    border: 2px solid green;
  }
</style>
<h1>Welcome <%= @user.email %></h1>

<div class="click">
<!-- <p>Click <%= link_to "here", new_register_path %> to register tournament you want to pacticipate</p> -->
<ul>
<li>Click <%= link_to "here", new_user_register_path(@user) %> to register tournament you want to pacticipate</li>

<li>Click <%= link_to "here", registers_path %> to see all registrations from others</li>
</ul>

</div>
<br>
<div class="show">
<p><strong>Tournaments you registered:</strong></p>

<table border="1">
  <tr>
    <th>Tournament Name</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Location</th>
  </tr>

  <tr>
    <td>
        <% @user.registers.each do |r| %>
          <%= r.tournament.name %>
          <br>
        <% end %>
    </td>

    <td>
        <% @user.registers.each do |r| %>
          <%= r.tournament.start_date %>
          <br>
        <% end %>
    </td>
    
    <td>
        <% @user.registers.each do |r| %>
          <%= r.tournament.end_date %>
          <br>
        <% end %>
    </td>

    <td>
        <% @user.registers.each do |r| %>
          <%= r.tournament.location %>
          <br>
        <% end %>
    </td>
    
  </tr>
  </table>
  <br>
  <br>
</div>


    
   
 